#!/bin/bash

# Some variables used in this script
PROFILE_NAME=default
KUIPER_TOP=../..
ADMIN_SCRIPTS=$KUIPER_TOP/scripts/admin
RUN_SCRIPTS=$KUIPER_TOP/scripts/run
CONSUL_DATA_DIR=/tmp/consul
CLUSTER_PORT=1443
PROFILE_NAME=default

function usage {
	echo Usage : $0 'options [ -h host ]';
	echo '  options can be a sequence of the following:';
	echo '      --host    (MANDATORY) : your machine name';
	echo '      --profile  (OPTIONAL) : defaults to "default"';
	echo '      --wait     (OPTIONAL) : consul wait time';
	echo '      --help                : print this usage';
	exit 1;
}

while [ $# -gt 0 ];
do
	[ "$1" == '--profile' ] && { PROFILE_NAME=$2; shift; }
	[ "$1" == '--host'    ] && { HOST=$2; shift; }
	[ "$1" == '--wait'    ] && { WAIT_TIME=$2; shift; }
	[ "$1" == '--help' ] && { usage; }

	shift;
done

#
# Check mandatories
#
[ -z `which gnatsd` ] && { echo gnatsd not found; exit 1; }
[ -z `which consul` ] && { echo consul not found; exit 1; }
[ "$PROFILE_NAME" == "" ] && usage;
[ "$HOST" == "" ] && usage;
[ -d $ADMIN_SCRIPTS ] || { echo "could not find $ADMIN_SCRIPTS"; exit 1; }


# Clean Startup, remove consul data and clear pm2
rm -rf $CONSUL_DATA_DIR
pm2 delete all

set -o errexit

#--------------NATS & CONSUL----------------------------

pm2 start --name _nats gnatsd --interpreter none -x
pm2 start --name _consul consul --interpreter none -x -- agent -server -bootstrap -data-dir $CONSUL_DATA_DIR -bind 127.0.0.1

[ -z "$WAIT_TIME" ] && WAIT_TIME=3

echo
echo waiting $WAIT_TIME seconds for consul to come up ...
sleep $WAIT_TIME

$ADMIN_SCRIPTS/conf-set --profile $RUN_SCRIPTS/templates/kv-kuiper.$PROFILE_NAME.yml --host $HOST

#------------Services-----------------------------------
# services used to be here

#------------Applications-------------------------------
# application used to be here
