#!/bin/bash

#
# Get canonical paths
#
export CWD_CANONICAL=$CWD
DIR=`dirname $0`
export DIR_CANONICAL=`cd $DIR; pwd`
. $DIR_CANONICAL/common.sh

#
# Usage
#
function usage {
	echo Usage : `basename $0` ' options';
	echo '      --val1 (MANDATORY)         : value 1';
	echo '      --val2 (OPTIONAL)          : value 2. defaults to 100';
	echo
	echo '  options can be a sequence of the following:';
	echo '      --help                     : print this help';
	echo

	exit 1;
}

#--------------------------------------------------------------
# Script specific code here
#--------------------------------------------------------------
TEMPLATE=$DIR_CANONICAL/templates/conf-global

#
# Process arguments
#
VALUE2=100

while [ $# -gt 0 ];
do
	case $1 in
		--help) usage;
			;;
		--val1) VALUE1=$2; shift;
			;;
		--val2) VALUE2=$2; shift;
			;;
		*) CONSUL_OPTIONS=$CONSUL_OPTIONS" "$1;
			;;
	esac
	shift;
done

#
# Check for mandatories
#
[ -z "$VALUE1" ] && usage;

EXPR=""
EXPR=$EXPR"val1=$VALUE1,"
EXPR=$EXPR"val2=$VALUE2,"

node $JS_DIR/generic-put.js --service conf --path /v1/config/global --template $TEMPLATE --sub $EXPR
