#!/bin/bash

#
# Get canonical paths
#
export CWD_CANONICAL=$CWD
__DIR=`dirname $0`
export DIR_CANONICAL=`cd $__DIR; pwd`
. $DIR_CANONICAL/common.sh

#
# Usage
#
function usage {
	echo Usage : `basename $0` ' options';
	echo
	echo '  options can be a sequence of the following:';
	echo '      [ consul startup options ] : any consul startup options (are opaquly passed to consul)';
	echo '      --fresh (OPTIONAL)         : forget everything and start';
	echo '      --help  (OPTIONAL)         : print this help';

	exit 1;
}

#
# Script specific code here
#
DATA_DIR=/tmp/consul

which consul > /dev/null || {
	echo '"consul" not installed. Do that and try again.'
	exit 1;
}

#
# Process arguments
#

while [ $# -gt 0 ];
do
	case $1 in
		--help) usage;
			;;
		--fresh) rm -rf $DATA_DIR;
			;;
		*) CONSUL_OPTIONS=$CONSUL_OPTIONS" "$1;
			;;
	esac
	shift;
done

#
# ensure that no previous instance of consul is running
#
CURR_INSTANCES=`pgrep -x consul`
[ -z "$CURR_INSTANCES" ] || echo Killing off previous instances : $CURR_INSTANCES
[ -z "$CURR_INSTANCES" ] || pkill -x -9 consul

#consul agent -server -data-dir $DATA_DIR $CONSUL_OPTIONS
consul agent -server -bootstrap -data-dir $DATA_DIR $CONSUL_OPTIONS
#consul agent -server -data-dir $DATA_DIR $CONSUL_OPTIONS
