#!/bin/bash

#
# Get canonical paths
#
export CWD_CANONICAL=$CWD
DIR=`dirname $0`
export DIR_CANONICAL=`cd $DIR; pwd`
. $DIR_CANONICAL/common.sh

#
# Usage
#
function usage {
	echo Usage : `basename $0` ' options';
	echo '      --service (MANDATORY)      : name of the service';
	echo
	echo '  options can be a sequence of the following:';
	echo '      --help                     : print this help';
	echo

	exit 1;
}

#--------------------------------------------------------------
# Script specific code here
#--------------------------------------------------------------
SERVICE=

#
# Process arguments
#

while [ $# -gt 0 ];
do
	case $1 in
		--help) usage;
			;;
		--service) SERVICE=$2; shift;
			;;
		*) CONSUL_OPTIONS=$CONSUL_OPTIONS" "$1;
			;;
	esac
	shift;
done

[ -z "$SERVICE" ] && usage;

node $JS_DIR/generic-service-get.js --service $SERVICE --path /common/revision
