#!/bin/bash

#
# Get canonical paths
#
export CWD_CANONICAL=$CWD
DIR=`dirname $0`
export DIR_CANONICAL=`cd $DIR; pwd`
. $DIR_CANONICAL/common.sh

#
# Usage
#
function usage {
	echo Usage : `basename $0` ' options';
	echo '      --id (MANDATORY)           : service id';
	echo ''
	echo '  options can be a sequence of the following:';
	echo '      --help                     : print this help';
	echo

	exit 1;
}

#--------------------------------------------------------------
# Script specific code here
#--------------------------------------------------------------
SERVICE_ID=

#
# Process arguments
#

while [ $# -gt 0 ];
do
	case $1 in
		--id) SERVICE_ID=$2; shift;
			;;
		--help) usage;
			;;
		*) CONSUL_OPTIONS=$CONSUL_OPTIONS" "$1;
			;;
	esac
	shift;
done

[ -z "$SERVICE_ID" ] && usage;

cd $JS_DIR
node -e 'require ("./service").deregister("'$SERVICE_ID'")'
