#!/bin/bash

#
# Get canonical paths
#
export CWD_CANONICAL=$CWD
DIR=`dirname $0`
export DIR_CANONICAL=`cd $DIR; pwd`
. $DIR_CANONICAL/common.sh

#
# Usage
#
function usage {
	echo Usage : `basename $0` ' options';
	echo
	echo '  options can be a sequence of the following:';
	echo '      --id (MANDATORY)           : id of the user';
	echo '      --old-password (MANDATORY) : old password of the user';
	echo '      --new-password (MANDATORY) : new password of the user';
	echo '      --help                     : print this help';
	echo

	exit 1;
}

#--------------------------------------------------------------
# Script specific code here
#--------------------------------------------------------------
TEMPLATE=$DIR_CANONICAL/templates/user-password-update

#
# Process arguments
#

while [ $# -gt 0 ];
do
	case $1 in
		--id) ID=$2; shift;
			;;
		--old-password) OLD=$2; shift;
			;;
		--new-password) NEW=$2; shift;
			;;	
		--help) usage;
			;;
		*) CONSUL_OPTIONS=$CONSUL_OPTIONS" "$1;
			;;
	esac
	shift;
done

#
# Check mandatories
#
[ -z "$ID" ] && usage;
[ -z "$OLD" ] && usage;
[ -z "$NEW" ] && usage;

cp $TEMPLATE $TMP
#
# Finger the template
#
sed -i 's,__ID__,'$ID',g' $TMP
sed -i 's,__OLD__,'$OLD',g' $TMP
sed -i 's,__NEW__,'$NEW',g' $TMP

node $JS_DIR/generic-post.js --service user --path /password/update --template $TMP

