#!/bin/bash

#
# Get canonical paths
#
export CWD_CANONICAL=$CWD
DIR=`dirname $0`
export DIR_CANONICAL=`cd $DIR; pwd`
. $DIR_CANONICAL/common.sh

#
# Usage
#
function usage {
	echo Usage : `basename $0` ' options';
	echo
	echo '  options can be a sequence of the following:';
	echo '      --id (MANDATORY)           : id of the user (format = id:auth_via, note that auth_via = "local" is the only option supported so far)';
	echo '      --fname (MANDATORY)        : first name of the user';
	echo '      --lname (MANDATORY)        : last name of the user';
	echo '      --email (MANDATORY)        : email of the user';
	echo '      --who (MANDATORY)          : who is creating this user';
	echo '      --help                     : print this help';
	echo

	exit 1;
}

#--------------------------------------------------------------
# Script specific code here
#--------------------------------------------------------------
TEMPLATE=$DIR_CANONICAL/templates/user-add

#
# Process arguments
#

while [ $# -gt 0 ];
do
	case $1 in
		--id) ID=$2; shift;
			;;
		--fname) FNAME=$2; shift;
			;;
		--lname) LNAME=$2; shift;
			;;
		--email) EMAIL=$2; shift;
			;;
		--who) WHO=$2; shift;
			;;
		--help) usage;
			;;
		*) CONSUL_OPTIONS=$CONSUL_OPTIONS" "$1;
			;;
	esac
	shift;
done

#
# Check mandatories
#
[ -z "$ID" ] && usage;
[ -z "$FNAME" ] && usage;
[ -z "$LNAME" ] && usage;
[ -z "$EMAIL" ] && usage;
[ -z "$WHO" ] && usage;

cp $TEMPLATE $TMP
#
# Finger the template
#
sed -i 's,__ID__,'$ID',g' $TMP
sed -i 's,__FNAME__,'$FNAME',g' $TMP
sed -i 's,__LNAME__,'$LNAME',g' $TMP
sed -i 's,__EMAIL__,'$EMAIL',g' $TMP
sed -i 's,__WHO__,'$WHO',g' $TMP

node $JS_DIR/generic-post.js --service user --path /admin/add --template $TMP
