#!/bin/bash

[ $# -lt 1 ] && { echo Usage: `basename $0` '<file-name-without-extension>'; exit 1; }

FILE_STEM=$1;

[ -f "$FILE_STEM".less ] || { echo file $FILE_STEM.less does not exist; exit 1; }

set -x
lessc $FILE_STEM.less --clean-css="--s1 --advanced --compatibility=ie8" $FILE_STEM.min.css
