#!/usr/bin/env node

require('app-module-path').addPath(__dirname + '/../../../');

var minimist      = require('minimist');
var mongoose      = require('apps/auth/common/db/mongoose');
var emitter       = mongoose.emitter;
var colors        = require('colors');
var path          = require('path');
var crypto        = require('crypto');
var model         = require('apps/auth/models/clients');
var client_schema = require('apps/auth/common/db/client-schema');
var locals        = require('common/kv');
var promise       = require('bluebird');

var mongo_url     = 'mongodb://localhost:27017/heimdallr?maxPoolSize=10';
var args          = minimist (process.argv.slice(2));

var params  = {};

function usage () {
	console.log (`Usage : ${path.basename (process.argv[1])} [ options ]`);
	console.log ('        --cid        (MANDATORY) : client id');

	process.exit (1);
}

function check_mandatories(key) {
	if (!args[key]) {
		console.log (colors.red (`Missing `) +  `: ${key} param mandatory`);
		usage ();
	}
}

check_mandatories ('cid');

emitter.on ('heimdallr.mongo.connected', function () {
	
	model.delete_client  (args['cid'], function (err, client) {
		if (err) {
			if (err.message)
				console.log (`${colors.red("error")} : ${err.message}`);
			else
				console.log (`${colors.red("error")} : ${err}`);

			process.exit (1);
		}

		if (client.n)
			console.log (colors.green(`client ${args['cid']} removed ok`));
		else
			console.log (colors.green(`client ${args['cid']} already removed`));

		process.exit (0);
	});
});
